# Generated by Django 4.2.1 on 2023-05-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproyecto', '0002_alter_anime_idanime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
